### ISSUE TITLE
Path must be a string. Received null

### ISSUE THREAD

**Issue by firedev** [karma-runner/karma-phantomjs-launcher#120]
I am having some issues configuring phantomJS for karma:

```
WARN [plugin]: Error during loading "karma-phantomjs-launcher" plugin:
  Path must be a string. Received null
...

WARN [launcher]: Can not load "PhantomJS", it is not registered!
  Perhaps you are missing some plugin?
```

Nothing special the `karma.js` is pretty simple:

```
    plugins: [
    ...
      'karma-phantomjs-launcher',
    ],
    browsers: ['PhantomJS']
...

```

I have found similar [question on SO](http://stackoverflow.com/questions/37412009/karma-error-during-loading-karma-phantomjs-launcher-plugin) but no replies.

What could go wrong? Thanks.

**Comment by firedev** [comment]
Too many open files. Reboot helped.

**Comment by firedev** [comment]
I guess it is related to the fact that I tried to use `phantomjs-prebuilt`. Here is what I did, installed `phantomjs` and added the following to karma.conf.js

process.env.PHANTOMJS_BIN = './node_modules/.bin/phantomjs'

**Comment by dignifiedquire** [comment]
If you are using phantomjs-prebuilt you should not need to set any env variables. Try removing your `process.env` line from the karma config.

**Comment by firedev** [comment]
If I use `phantomjs-prebuilt` I get the error above, probably because of  `import { path } from 'phantomjs'` or a similar construct somewhere. So I have replaced it with `phantomjs` but then karma complains it can't find phantomjs executable so I had to nail it down. 

Just to be clear - it is working, feel free to close the issue.

**Comment by dignifiedquire** [comment]
okay thanks, closing this then. feel free to post any questions/issues though

**Comment by herrevilkitten** [comment]
I just got this error.  After some investigation, I found that karma-phantomjs-launcher worked with phantomjs-prebuilt "2.1.7" but not "^2.1.7".  I haven't investigated any more than this, since it's working now :)

**Comment by philjones88** [comment]
I'm hitting the same issue. Installed globally `phantomjs-prebuilt` 2.1.1 and get the same error message.

**Comment by philjones88** [comment]
Figuring out that `phantomjs-prebuilt` is path null...

```
$ node
> console.log(require('phantomjs-prebuilt'));
{ path: null, version: '2.1.1', cleanPath: [Function] }
undefined
>
```

**Comment by Yantrio** [comment]
I seem to be hitting the same issue too, maybe it's worth re-opening the issue?

**Comment by evfender** [comment]
+1 to reopen. Running:
jenkins 2.16
node 6.3.1
karma 1.1.2
phantomjs-prebuilt 2.1.9

```
[31m05 08 2016 08:14:28.668:ERROR [plugin]: [39mError during loading "/var/lib/jenkins/workspace/project/node_modules/karma-phantomjs-launcher" plugin:
  Path must be a string. Received null
```

**Comment by evfender** [comment]
***Update:***
If I roll back karma-phantomjs-launcher to the last version I had installed (0.2.3) before upgrading to the latest, uninstall phantomjs-prebuilt and reinstall phantomjs, everything installs and tests are run in Jenkins and locally just fine.

**Comment by AngusFu** [comment]
@philjones88  is right. Add  `require('phantomjs-prebuilt').path = './node_modules/.bin/phantomjs';`  to `karma.conf.js`, the problem disappears. Yet another problem rises, where “PhantomJS have not captured in 60000 ms, killing”... Quite annoying... In Chinese we call such situation "hardly have one gourd been pushed under water when another bobs up(按下葫芦浮起瓢)", it means "solve one problem only to find another cropping up"...

**Comment by McGiogen** [comment]
I fixed simply deleting all node_modules and calling "npm install" another time.

**Comment by grofit** [comment]
Same issue today, just tried removing all node modules and re installing which did stop the error but as @AngusFu says I now just have PhantomJS not starting, if I check the command line `phantomjs -v` returns 2.1.1 and phantom prebuilt seems to be installed ok.

**Comment by recurrence** [comment]
Upgrading to latest phantomjs-prebuilt (2.1.13) fixed this error for me.

**Comment by moshie** [comment]
This issue is still present needs resolving as it breaks angular testing suite :(

**Comment by AdamYee** [comment]
In my case, I was running `npm i --ignore-scripts` on my CI build server. Locally, things worked without the --ignore-scripts. It works now in TeamCity without --ignore-scripts. I suspect that disallowing postinstall scripts to run could be the cause for some people.

**Comment by cbrwizard** [comment]
Also having this issue. Upgrading to the phantomjs-prebuilt@2.1.13 and karma-phantomjs-launcher@1.0.2 did not help. Adding a line `process.env.PHANTOMJS_BIN = './node_modules/.bin/phantomjs'` to `karma.conf` did not help either.

**Comment by gabyvs** [comment]
I am facing the same issue and I am in the same path as @cbrwizard (using yarn). I didn't want to do `npm install` instead of `yarn`, because that takes forever while yarn is really quick. I also wanted to take advantage of yarn and make our CI jobs faster.

I solved it by running `yarn`, which would install my dependencies, then running `npm install phantomjs-prebuilt`, and then I can run `yarn test` successfully.

What I noticed is that if I just run `npm install` and then `npm test` all the tests would work, but running `yarn` and then `yarn test` would make the tests fail. I think the difference between both is that running `npm install` will execute the file install.js inside phantomjs-prebuilt, while, for some reason, that script is not executed when running `yarn`. So, by running `npm install phantomjs-prebuilt` after running `yarn` will force the execution of install.js script...  

I don't know if that will be useful for you guys, but posting it here just in case it helps somebody.

**Comment by lunaryorn** [comment]
I'm saw the same issue, but was able to fix it without resorting to npm by

1. Removing `node_modules/`
2. Removing the yarn cache (`~/Library/Caches/Yarn` on MacOS, `~/.cache/yarn` on Linux)
3. `yarn`
4. `yarn test`

Step 2 is crucial for whatever weird reason:  Just removing `node_modules` was not enough.

**Comment by jcarbo** [comment]
@gabyvs - your solution worked for me. However, you can avoid calling `npm install` by just running the `install.js` as a `postinstall` script:

```
"scripts": {
  // other scripts
  "postinstall": "node node_modules/phantomjs-prebuilt/install.js"
}
```

Now calling `yarn` will always run `node_modules/phantomjs-prebuilt/install.js` as the last step.

**Comment by nadavsinai** [comment]
fix by running
```
 npm rebuild phantom-prebuilt
````

**Comment by AlexandreBonneau** [comment]
> Now calling `yarn` will always run `node_modules/phantomjs-prebuilt/install.js` as the last step.

Indeed it will **always** try to access that file, even if it does not exists, which means it would fail in the latter case.

Adding that `postinstall` line means that you will absolutely require that the `install.js` file be always present, otherwise the `yarn install` (or `npm install`) command will fail.

If the `phantomjs-prebuilt` dependency is a dev dependency, then using your project as a *regular* dependency will omit it, hence the `node_modules/phantomjs-prebuilt/install.js` will be missing (cf. problem example [here](https://github.com/BobKnothe/autoNumeric/issues/367)).

I have yet to find a automated way to fix that problem.

**Comment by martynchamberlin** [comment]
This is what got this working for me: 
```
yarn add --force phantomjs-prebuilt
```

**Comment by mikefisher84** [comment]
thanks @martynchamberlin I tried every solution in here and this is what worked for me too. Using yarn 0.20.3 and karma 1.5.0

**Comment by jfstephe** [comment]
This is a note for myself as much as anyone else. Having had this issue several times over the last 6 months (using npm not yarn), I had fixed the version of karma-phantomjs-launcher to 0.2.3 which seemed to fix it. When I rebuilt my Jenkins box this stopped working. I'd obviously forgotten to sacrifice a goat or something BUT because I'd fixed the version I missed out on the fix!

Version [1.0.2](https://github.com/karma-runner/karma-phantomjs-launcher/blob/master/CHANGELOG.md) (available for a few months!) has the fix in that resolved this for me.

**Comment by StefH** [comment]
@martynchamberlin : did you just do this locally on your system, or did you do this during Travis build?

**Comment by martynchamberlin** [comment]
@StefH Only tried locally. I didn't test it elsewhere. 

To be honest, phantomJS is so ancient and slow that ultimately we decided to move to a browserless implementation of mocha and JSDOM. [Here's a good comparison](https://www.npmjs.com/package/jsdom#jsdom-vs-phantomjs) that breaks down PhantomJS vs JSDOM.

**Comment by heiliuer** [comment]
I remove node-modules/phantomjs-prebuilt then run npm install, and fix it!

**Comment by benadamstyles** [comment]
This is still happening, why is it closed?

**Comment by levino** [comment]
Same here. Something fishy going on.

**Comment by AlexandreBonneau** [comment]
For info, I created a workaround for that problem by calling the following `yarnfix.js` script (https://github.com/autoNumeric/autoNumeric/blob/master/yarnfix.js) on each postinstall:
```js
"postinstall": "node yarnfix.js",
```

**Comment by yagudaev** [comment]
Reopen. Still happening with `phantomjs-prebuilt: ^2.1.14` and `"karma-phantomjs-launcher": "^1.0.4"` on CircleCI

A good way to recreate it is to change the following `karma-phantomjs-launcher/index.js`:

```
var phantomJSExePath = function () {
  // If the path we're given by phantomjs is to a .cmd, it is pointing to a global copy.
  // Using the cmd as the process to execute causes problems cleaning up the processes
  // so we walk from the cmd to the phantomjs.exe and use that instead.
  var phantomSource = null
  // ******** looks like the path of the prebuilt is equal to null for some reason ******
  // var phantomSource = require('phantomjs-prebuilt').path
```

Looking at `phantomjs-prebuilt/lib/phantomjs.js`:

```
/**
 * Where the phantom binary can be found.
 * @type {string}
 */
try {
  var location = require('./location')
  exports.path = path.resolve(__dirname, location.location)
  exports.platform = location.platform
  exports.arch = location.arch
} catch(e) {
  // Must be running inside install script.
  exports.path = null
}
```

Which means on of the two first lines in that try block caused an exception because the path could not be resolved.

I am using node 6.7.0 on CI server and node 7.8.0 locally (without a problem). Might also be a node/npm version dependent.

**Comment by yagudaev** [comment]
If you are using Karma it will swallow the exception and return a zero error code which will result in your CI build passing. Got a PR for it up https://github.com/karma-runner/karma/pull/2672.

You can try using that fork by running:

```
yarn remove karma
yarn add nano3labs/karma.git#bail-on-load-error
```

Your CI should at least fail now.

**Comment by spencer-brown** [comment]
Having this same issue with yarn@0.23.2, karma-phantomjs-launcher@1.0.4, phantomjs-prebuilt@2.1.14, karma@1.6.0.

Can you please re-open this issue, @dignifiedquire ?

**Comment by SimenB** [comment]
#191 trying to fix this, or at least provide a better error message

**Comment by andrewchilds** [comment]
This fixed it for me:

```sh
rm -rf node_modules
yarn
```

¯\_(ツ)_/¯

**Comment by yagudaev** [comment]
Any idea why it breaks to begin with @SimenB? Is it a mis-configured CI where the binary doesn't get installed properly or at the wrong time?

**Comment by SimenB** [comment]
I _think_ the issue is that the current method for finding the path (`require('phantomjs-prebuilt').path`) relies on a `postinstall` hook which for some reason isn't always ran, and/or its result isn't cached properly.

https://github.com/Medium/phantomjs/blob/750d5f32e1586fe0b34c782dd87f60cbb21e6441/lib/phantomjs.js#L14-L26

I'd guess running `yarn --force` (or `yarn add phantomjs-prebuilt --force`) instead of just `yarn` on CI should fix most of the issues people see. Basically force all `postinstall` hooks to run even if yarn thinks they're not necessary.

(or `npm rebuild phantomjs-prebuilt` as stated above if using npm)

**Comment by yagudaev** [comment]
Thanks @SimenB added

```
# circle.yml
test:
  override:
    # force yarn to install phantomjs https://github.com/karma-runner/karma-phantomjs-launcher/issues/120#issuecomment-296924189
    - yarn --force
    - yarn test
    - yarn run lint
```

To our and using a forked version of karma@v1.3.0

```
yarn add nano3labs/karma.git#bail-on-load-error-1-3-0
```

Will report here how it works for our team. Hopefully, it will be a good enough workaround for the time being.

**Comment by StefH** [comment]
@andrewchilds 
This did indeed solve it (for now)...
See https://travis-ci.org/StefH/string-split-join

**Comment by SimenB** [comment]
Probably related: yarnpkg/yarn#1955

**Comment by ericjames** [comment]
@SimenB Running `npm rebuild phantomjs-prebuilt` solved it

**Comment by hiteshaneja** [comment]
This happens when your `phantomjs-prebuilt` install is unable to run the `install` script of the package for some reason (_For e.g. npm i run using --ignore-scripts flag etc_.). What this install script does is install phantomjs on your machine (if not already installed) and creates a file called `location.js`  inside the lib folder. The content of the `location.js` file looks something like this

```
module.exports.location = "C:\\dev\\phantomjs\\phantomjs-2.1.1-windows\\bin\\phantomjs.EXE"
module.exports.platform = "win32"
module.exports.arch = "x64"
```

phantomjs-launcher uses these properties to run phantomjs and if it is not found you see error "Path must be string"

So check if location.js exists inside the lib folder under phantomjs-prebuilt or not, if not, run 
```
node node_modules/phantomjs-prebuilt/install.js
```

**Comment by andrewchilds** [comment]
Confirming that adding a `- yarn --force` line to our circle.yml file's `test` section fixed this issue for us:

```
test:
  override:
    # force yarn to install phantomjs
    # https://github.com/karma-runner/karma-phantomjs-launcher/issues/120
    - yarn --force
    - yarn test
```

**Comment by adreyfus** [comment]
I had the error `Error during loading "karma-phantomjs-launcher" plugin: Path must be a string. Received null`,  and adding `phantomjs-prebuilt ^2.1.8` to the dependencies of the project resolved the problem.

**Comment by MrRaindrop** [comment]
`npm install phantomjs-prebuilt` solved my problem with the same error message. Turns out the network breaking down caused none phantom was built in the system.

**Comment by jackson-chris** [comment]
Just experienced this issue recently as well. Adding dependency on `"phantomjs-prebuilt": "2.1.8"` resolved the issue.

**Comment by johnzhu12** [comment]
@martynchamberlin your solution works for me.thanks..at first,I found the phantomSource is null in index.js of karma-phantom-launcher. 
  var phantomSource = require('phantomjs-prebuilt').path //phantomSource is null
  phantomSource ＝ phantomSource?phantomSource:"" //I add this line and the problem gone 
 
 so,just try this one:   yarn add --force phantomjs-prebuilt

**Comment by krasimir** [comment]
Just to confirm that `2.1.8` version fixed the issue to me as well.

**Comment by ptim** [comment]
`npm rebuild phantom-prebuilt` is the most satisfying solution for me, because I appreciate the progress bar. Running `yarn add --force phantomjs-prebuilt` appears to hang (but would probably resolve...). Thanks all for the informative thread!

I'm encountering this on OSX:
```
"karma-phantomjs-launcher": "^1.0.2",
"phantomjs-prebuilt": "^2.1.13",
```

**Comment by naganowl** [comment]
Ran into this problem locally with `yarn` and resolved it by running the following

```
yarn cache clean
rm -rf node_modules/
yarn install
```

There are similar steps that can be done with `npm`. I believe the root cause of this issue is a shared cache for the binary which is used/shared across multiple projects. I bring this up because I have another project that's using the binary and it appears the package cache may be having problems when switching between projects.

Seems like similar suggestions have already been stated above, figure that this might help someone in the future though!

**Comment by abngal** [comment]
I solved it by preventing low disk space warnings/error.
It was failing on my teamcity container because my host OS has less the 3GB left warnings when phantomjs-prebuilt was being installed.
My folder node_modules/phantomjs-prebuilt/lib/ has incomplete files (due to npm install silent-fail )
https://github.com/Medium/phantomjs/issues/533#issuecomment-210913070

**Comment by MrChanLi2013** [comment]
I use `npm rebuild`.It work!

**Comment by moonpatroller** [comment]
> @philjones88 is right. Add `require('phantomjs-prebuilt').path = './node_modules/.bin/phantomjs';` to `karma.conf.js`, the problem disappears. Yet another problem rises, where “PhantomJS have not captured in 60000 ms, killing”... Quite annoying... In Chinese we call such situation "hardly have one gourd been pushed under water when another bobs up(按下葫芦浮起瓢)", it means "solve one problem only to find another cropping up"...

Sounds like whack-a-mole.
